#[derive(Debug, PartialEq)]
pub enum Token<'a> {
    LBrace,
    RBrace,
    LBracket,
    RBracket,
    LParen,
    RParen,
    LessThan,
    GreaterThan,
    Dot,
    Annotation,
    QuestionMark,
    Comma,

    /// Literals are `true`, `false`, numeric, string, char literals.
    Literal(&'a str),
    Identifier(&'a str),
    Keyword(Keyword),
    Semicolon,
    /// Assignment token includes `=`, `-=`, `+=`, `*=`, `/=`,
    /// `%=`, `&=`, `|=`, `^=`, `<<=`, `>>=`, `>>>=`
    Assignment(&'a str),
    Op(&'a str),
    EOF,
}

#[derive(Debug, PartialEq)]
pub enum Keyword {
    Public,
    Private,
    Protected,
    Abstract,
    Const,
    Default,
    Enum,
    Extends,
    Final,
    Implements,
    Import,
    Interface,
    Package,
    Static,
    Synchronized,
    Transient,
    Return,
    Void,
    If,
    Else,
    While,
    For,
    New,
    This,
    Super,
    Break,
    Continue,
    Case,
    Try,
    Catch,
    Do,
    Finally,
    InstanceOf,
    Native,
    Switch,
    Throw,
    Throws,
    Volatile,
}
